# Generated by Django 3.1.7 on 2021-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210517_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='room_code',
            field=models.CharField(default='D102BAC', max_length=7, unique=True),
        ),
    ]
