# Generated by Django 3.1.7 on 2021-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210722_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='room_code',
            field=models.CharField(default='E4A0228', max_length=7, unique=True),
        ),
    ]
