# Generated by Django 3.1.7 on 2021-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210723_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='room_code',
            field=models.CharField(default='4EF5160', max_length=7, unique=True),
        ),
    ]
