# Generated by Django 3.1.7 on 2021-07-26 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0006_auto_20210723_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='room_code',
            field=models.CharField(default='89804BF', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invitation_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
