# Generated by Django 3.1.7 on 2021-08-17 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0007_auto_20210726_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='room_code',
            field=models.CharField(default='60AD28D', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
