# Generated by Django 3.1.7 on 2021-08-17 12:50

import campaign.models.campaign
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20210817_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='room_code',
            field=models.CharField(default=campaign.models.campaign.room_code_gen, max_length=7, unique=True),
        ),
    ]
