# Generated by Django 3.1.7 on 2021-03-01 18:38

import configuration.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('given_names', models.CharField(blank=True, max_length=127, null=True)),
                ('last_name', models.CharField(blank=True, max_length=127, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(default=configuration.utils.tz_now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
