# Generated by Django 3.1.7 on 2021-03-01 22:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference',
            field=models.CharField(default=user.models.reference_generator, max_length=10, unique=True),
        ),
    ]
